import itertools

import numpy as np
import scipy.sparse as sp
import openmdao.api as om

from dymos.utils.lagrange import lagrange_matrices


class BarycentricLagrangeInterpComp(om.ExplicitComponent):
    """
    Class definition for BarycentricLagrangeInterpComp.

    Give a vector of input value at some set of nodes, a time span of the
    interpolating polynomial, and a desired time of interpolation, interpolate the
    value and derivatives of a polynomial generated by the original states.

    This method uses Lagrange Barycentric Interpolation and should be reasonably numerically
    stable.

    Parameters
    ----------
    grid_data : GridData
        A GridData instance that details information on how the control input and discretization
        nodes are layed out.
    standalone_mode : bool
        If True, this component runs its configuration steps during setup. This is useful for
        unittests in which the component does not exist in a larger group.
    **kwargs
        Keyword arguments passed to ExplicitComponent.
    """
    def __init__(self, grid_data, standalone_mode=False, time_units=None, **kwargs):
        self._segment_index = 0
        self._grid_data = grid_data
        self._vec_size = 1
        self._time_units = time_units

        self._standalone_mode = standalone_mode
        self._interpolants = {}
        self._controls = {}

        self._w_b_i = {}
        self._tau_i = {}
        self._l_idxs_from_g = {}
        self._dl_dg_idxs_from_g = {}

        # Lagrange matrix nomenclature
        # L_da : Given values at input nodes, interpolate to all nodes
        # D_aa : Given values at all nodes, interpolate derivative to all nodes
        # D2_aa : Given values at all nodes, interpolate second derivative to all nodes
        self._L_da = {}  # Interpolation matrices
        self._D_da = {}  # Differentiation matrices
        self._D_aa = {}  # Differentiation matrices
        self._D2_aa = {}  # Second derivative differentiation matrices

        # The Lagrange interpolation matrix L_id maps control values as given at the input nodes
        # to values at the discretization nodes.
        num_disc_nodes = grid_data.subset_num_nodes['control_disc']
        num_input_nodes = grid_data.subset_num_nodes['control_input']
        self._L_id = np.zeros((num_disc_nodes, num_input_nodes), dtype=float)
        self._L_id[np.arange(num_disc_nodes, dtype=int),
                   self._grid_data.input_maps['dynamic_control_input_to_disc']] = 1.0

        self._disc_node_idxs_by_segment = []
        self._input_node_idxs_by_segment = []

        first_disc_node_in_seg = 0
        for seg_idx in range(self._grid_data.num_segments):
            ncin = grid_data.subset_num_nodes_per_segment['control_input'][seg_idx]
            n = grid_data.subset_num_nodes_per_segment['all'][seg_idx]
            i1_ci, i2_ci = self._grid_data.subset_segment_indices['control_input'][seg_idx, :]
            i1_all, i2_all = self._grid_data.subset_segment_indices['all'][seg_idx, :]
            seg_control_input_idxs = self._grid_data.subset_node_indices['control_input'][i1_ci:i2_ci]
            seg_control_disc_idxs = self._grid_data.subset_node_indices['control_disc'][i1_ci:i2_ci]
            seg_all_idxs = self._grid_data.subset_node_indices['all'][i1_all:i2_all]
            w_b_i = self._w_b_i[seg_idx] = np.ones(n)
            tau_i = self._tau_i[seg_idx] = grid_data.node_stau[seg_all_idxs]

            # Number of control discretization nodes per segment
            ncdnps = grid_data.subset_num_nodes_per_segment['control_disc'][seg_idx]
            ar_control_disc_nodes = np.arange(ncdnps, dtype=int)
            disc_idxs_in_seg = first_disc_node_in_seg + ar_control_disc_nodes
            first_disc_node_in_seg += ncdnps

            # The indices of the discretization node u vector pertaining to the given segment
            self._disc_node_idxs_by_segment.append(disc_idxs_in_seg)

            # The indices of the input u vector pertaining to the given segment
            self._input_node_idxs_by_segment.append(
                grid_data.input_maps['dynamic_control_input_to_disc'][disc_idxs_in_seg])

            for j in range(n):
                for k in range(n):
                    if k != j:
                        w_b_i[j] /= (tau_i[j] - tau_i[k])

            self._l_idxs_from_g[seg_idx] = list(itertools.combinations(range(n)[::-1], n - 1))

            # These indices pertain to the upper triangular matrix (excluding the diagonal)
            self._dl_dg_idxs_from_g[seg_idx] = []
            for i, tup in enumerate(self._l_idxs_from_g[seg_idx]):
                self._dl_dg_idxs_from_g[seg_idx].extend(list(itertools.combinations(tup, n - 2))[i:])

            if n not in self._L_da:
                tau_cd_idxs = seg_control_disc_idxs - seg_control_disc_idxs[0]
                self._L_da[n], self._D_da[n] = lagrange_matrices(tau_i[tau_cd_idxs], tau_i)

                _, self._D_aa[n] = lagrange_matrices(tau_i, tau_i)
                self._D2_aa[n] = np.dot(self._D_aa[n], self._D_aa[n])

        super().__init__(**kwargs)

    def setup(self):
        self.add_input('stau', shape=(self._vec_size,), units='unitless')
        self.add_input('t_duration', shape=(1,), units=self._time_units)
        if self._standalone_mode:
            # If in standalone_mode, assume interpolants were added prior to setup.
            self.configure_io()

    def set_segment_index(self, segment_index):
        """
        Set the index of the segment to be interpolated.

        Parameters
        ----------
        segment_index : int
            The index of the segment for which the interpolation is to be performed.
        """
        gd = self._grid_data
        self._segment_index = segment_index
        self._dptau_dstau = 0.5 * (gd.segment_ends[segment_index + 1] - gd.segment_ends[segment_index])

        ncin_ps = gd.subset_num_nodes_per_segment['control_input']
        ncin_s = ncin_ps[self._segment_index]

        # The indices of the control input pertaining to the given segment.
        self._seg_ci_idxs = np.sum(ncin_ps[:self._segment_index], dtype=int) + \
                                   np.arange(ncin_s, dtype=int)

        disc_node_idxs = self._disc_node_idxs_by_segment[self._segment_index]
        input_node_idxs = self._input_node_idxs_by_segment[self._segment_index]
        self._L_id_seg = self._L_id[disc_node_idxs[0]:disc_node_idxs[0] + len(disc_node_idxs),
                         input_node_idxs[0]:input_node_idxs[0] + len(input_node_idxs)]

    def add_control_interp(self, control_name, shape, units):
        """
        Add a variable to be interpolated at configure time.

        Parameters
        ----------
        name : str
            A name associated with the interpolant.
        input_name : str
            The name of the input containing values to be interpolated at the nodes.
        output_name : str
            The name of the output containing the value interpolated at some given tau.
        shape : tuple
            The shape of the variable to be interpolated.
        units : str
            The units of the variable to be interpolated.
        """
        if control_name in self._controls:
            raise ValueError(f'{self.msginfo} : Attempted to add control named {control_name} but one already exists.')

        self._controls[control_name] = {'input_name': f'controls:{control_name}',
                                        'output_name': f'control_values:{control_name}',
                                        'output_rate_name': f'control_rates:{control_name}_rate',
                                        'output_rate2_name': f'control_rates:{control_name}_rate2',
                                        'shape': shape,
                                        'units': units}

    def configure_io(self):
        """
        Final configuration of the components inputs and outputs typically called during configure of some
        parent Group.
        """
        ncin = self._grid_data.subset_num_nodes['control_input']
        num_nodes = self._grid_data.subset_num_nodes['all']

        for control_name, options in self._controls.items():
            input_name = options['input_name']
            output_name = options['output_name']
            output_rate_name = options['output_rate_name']
            output_rate2_name = options['output_rate2_name']
            shape = options['shape']
            units = options['units']

            self.add_input(input_name, shape=(ncin,) + shape, units=units)
            self.add_output(output_name, shape=(self._vec_size,) + shape, units=units)
            self.add_output(output_rate_name, shape=(self._vec_size,) + shape, units=units)
            self.add_output(output_rate2_name, shape=(self._vec_size,) + shape, units=units)

            self.declare_partials(of=output_name, wrt=input_name, val=0.0)
            self.declare_partials(of=output_rate_name, wrt=input_name, val=0.0)
            self.declare_partials(of=output_rate2_name, wrt=input_name, val=0.0)
            self.declare_partials(of=output_name, wrt='stau', val=0.0)
            self.declare_partials(of=output_rate_name, wrt='stau', val=0.0)
            self.declare_partials(of=output_rate2_name, wrt='stau', val=0.0)
            # self.declare_partials(of=output_name, wrt='t_duration', val=0.0)
            self.declare_partials(of=output_rate_name, wrt='t_duration', val=0.0)
            self.declare_partials(of=output_rate2_name, wrt='t_duration', val=0.0)

    def compute(self, inputs, outputs):
        """
        Compute component outputs.

        Parameters
        ----------
        inputs : `Vector`
            `Vector` containing inputs.
        outputs : `Vector`
            `Vector` containing outputs.
        """
        i1_ci, i2_ci = self._grid_data.subset_segment_indices['control_input'][self._segment_index, :]
        w_b_i = self._w_b_i[self._segment_index]
        tau_i = self._tau_i[self._segment_index]
        seg_ci_idxs = self._grid_data.subset_node_indices['control_input'][i1_ci:i2_ci]

        # The number of control input nodes in this segment
        ncin_s = self._grid_data.subset_num_nodes_per_segment['control_input'][self._segment_index]

        i1_all, i2_all = self._grid_data.subset_segment_indices['all'][self._segment_index, :]
        seg_all_idxs = self._grid_data.subset_node_indices['all'][i1_all:i2_all]

        n = seg_all_idxs.size

        tau = inputs['stau']
        g = tau - tau_i

        # l_idxs_from_g = list(itertools.combinations(range(n)[::-1], n - 1))

        # This code block is replaced by precomputing the combinations of g that are multiplied to
        # form elements in l (l_idxs_from_g).
        # These indices are precomputed at setup and cached.
        # This makes evaluation about 3x faster when n=200.

        # n = len(seg_node_idxs)
        # for i in range(n):
        #     for j in range(n):
        #         if j != i:
        #             l[i] *= g[j]

        l = np.prod(g[self._l_idxs_from_g[self._segment_index]], axis=1)

        dt_dstau = inputs['t_duration'] * self._dptau_dstau
        u_idxs = self._input_node_idxs_by_segment[self._segment_index]

        for control, options in self._controls.items():
            u_in = inputs[options['input_name']][u_idxs, ...]
            # u_hat = np.dot(self._L_da[n] @ self._L_id_seg, u_in) # radau
            u_hat = np.dot(self._L_id_seg, u_in) # gauss-lobatto
            udot_hat = np.dot(self._D_aa[n], u_hat) / dt_dstau
            udot2_hat = np.dot(self._D2_aa[n], u_hat) / dt_dstau ** 2

            wbu = np.swapaxes(w_b_i * np.swapaxes(u_hat, 0, -1), -1, 0)
            outputs[options['output_name']] = np.einsum('i,ij...->j...', l, wbu)  # u

            wbu_dot_hat = np.swapaxes(w_b_i * np.swapaxes(udot_hat, 0, -1), -1, 0)
            outputs[options['output_rate_name']] = np.einsum('i,ij...->j...', l, wbu_dot_hat)  # u_dot

            wbu_dot2_hat = np.swapaxes(w_b_i * np.swapaxes(udot2_hat, 0, -1), -1, 0)
            outputs[options['output_rate2_name']] = np.einsum('i,ij...->j...', l, wbu_dot2_hat)  # u_dot2

    def compute_partials(self, inputs, partials, discrete_inputs=None):
        i1, i2 = self._grid_data.subset_segment_indices['all'][self._segment_index, :]
        w_b_i = self._w_b_i[self._segment_index]
        tau_i = self._tau_i[self._segment_index]
        seg_node_idxs = self._grid_data.subset_node_indices['all'][i1:i2]
        n = len(seg_node_idxs)

        tau = inputs['stau']

        g = tau - tau_i
        dg_dtau = np.ones_like(tau_i)
        dl_dg = np.zeros((n, n))
        # As above, we replace these nested loops to improve performance as n becomes large.
        # l = np.ones_like(g, dtype=float)
        # for i in range(n):
        #     for j in range(n):
        #         if j != i:
        #             l[i] *= g[j]
        #             dl_dg[i, j] = 1.0
        #             for k in range(n):
        #                 if k != j and k != i:
        #                     dl_dg[i, j] *= g[k]

        dl_dg[np.triu_indices_from(dl_dg, k=1)] = np.prod(g[self._dl_dg_idxs_from_g[self._segment_index]], axis=1)
        dl_dg = dl_dg + dl_dg.T
        l = np.prod(g[self._l_idxs_from_g[self._segment_index]], axis=1)

        dt_dstau = inputs['t_duration'] * self._dptau_dstau
        ddt_dstau_dt_duration = self._dptau_dstau

        u_idxs = self._input_node_idxs_by_segment[self._segment_index]

        for control_name, options in self._controls.items():
            u_in = inputs[options['input_name']][u_idxs, ...]
            # u_hat = self._L_da[n] @ np.dot(self._L_id_seg, u_in) # radau-ps
            u_hat = np.dot(self._L_id_seg, u_in) # gauss-lobatto
            udot_hat = np.dot(self._D_aa[n], u_hat) / dt_dstau
            udot2_hat = np.dot(self._D2_aa[n], u_hat) / dt_dstau ** 2

            shape = options['shape']
            size = np.prod(shape, dtype=int)

            wbu_hat = np.swapaxes(w_b_i * np.swapaxes(u_hat, 0, -1), -1, 0)
            du_dl = wbu_hat.T
            partials[options['output_name'], 'stau'] = du_dl @ dl_dg @ dg_dtau

            wbudot_hat = np.swapaxes(w_b_i * np.swapaxes(udot_hat, 0, -1), -1, 0)
            dudot_dl = wbudot_hat.T
            partials[options['output_rate_name'], 'stau'] = dudot_dl @ dl_dg @ dg_dtau

            wbudot2_hat = np.swapaxes(w_b_i * np.swapaxes(udot2_hat, 0, -1), -1, 0)
            dudot2_dl = wbudot2_hat.T
            partials[options['output_rate2_name'], 'stau'] = dudot2_dl @ dl_dg @ dg_dtau

            du_dwbu_hat = l
            d_wbuhat_d_uhat = w_b_i
            # duhat_du_in = self._L_da[n] @ self._L_id_seg  # radau
            duhat_du_in = self._L_id_seg  # gauss-lobatto

            du_du_in = np.kron((du_dwbu_hat * d_wbuhat_d_uhat) @ duhat_du_in, np.eye(size))
            # First fill the partials with zeros so that stale values from previous calls are not present.
            partials[options['output_name'], options['input_name']][...] = 0.0
            partials[options['output_rate_name'], options['input_name']][...] = 0.0
            partials[options['output_rate2_name'], options['input_name']][...] = 0.0

            partials[options['output_name'], options['input_name']][..., u_idxs] = du_du_in

            dudot_dwbudot_hat = l
            d_wbudot_hat_d_udot_hat = w_b_i
            dudot_hat_duhat = self._D_aa[n] / dt_dstau

            dudot_du_in = sp.kron((dudot_dwbudot_hat * d_wbudot_hat_d_udot_hat) @ dudot_hat_duhat @ duhat_du_in,
                                  sp.eye(size))
            partials[options['output_rate_name'], options['input_name']][..., u_idxs] = dudot_du_in.todense()

            dudot_hat_ddt_dstau = -udot_hat / dt_dstau
            partials[options['output_rate_name'], 't_duration'] = (dudot_dwbudot_hat * d_wbudot_hat_d_udot_hat) @ dudot_hat_ddt_dstau * ddt_dstau_dt_duration

            dudot2_dwbudot2_hat = l
            d_wbudot2_hat_d_udot2_hat = w_b_i
            dudot2_hat_duhat = self._D2_aa[n] / dt_dstau ** 2

            dudot2_du_in = sp.kron((dudot2_dwbudot2_hat * d_wbudot2_hat_d_udot2_hat) @ dudot2_hat_duhat @ duhat_du_in,
                                   sp.eye(size))
            partials[options['output_rate2_name'], options['input_name']][..., u_idxs] = dudot2_du_in.todense()

            dudot2_hat_ddt_dstau = -2 * udot2_hat / dt_dstau
            partials[options['output_rate2_name'], 't_duration'] = (dudot_dwbudot_hat * d_wbudot_hat_d_udot_hat) @ dudot2_hat_ddt_dstau * ddt_dstau_dt_duration
