import itertools

import numpy as np
import openmdao.api as om


class BarycentricLagrangeInterpComp(om.ExplicitComponent):
    """
    Class definition for BarycentricLagrangeInterpComp.

    Give a vector of input value at some set of nodes, a time span of the
    interpolating polynomial, and a desired time of interpolation, interpolate the
    value and derivatives of a polynomial generated by the original states.

    This method uses Lagrange Barycentric Interpolation and should be reasonably numerically
    stable.

    Parameters
    ----------
    grid_data : GridData
        A GridData instance that details information on how the control input and discretization
        nodes are layed out.
    standalone_mode : bool
        If True, this component runs its configuration steps during setup. This is useful for
        unittests in which the component does not exist in a larger group.
    **kwargs
        Keyword arguments passed to ExplicitComponent.
    """
    def __init__(self, grid_data, standalone_mode=False, **kwargs):
        self._segment_index = 0
        self._grid_data = grid_data
        self._vec_size = 1

        self._standalone_mode = standalone_mode
        self._interpolants = {}

        self._w_b_i = {}
        self._tau_i = {}
        self._l_idxs_from_g = {}
        self._dl_dg_idxs_from_g = {}

        for seg_idx in range(self._grid_data.num_segments):
            n = grid_data.subset_num_nodes_per_segment['all'][seg_idx]
            i1, i2 = self._grid_data.subset_segment_indices['all'][seg_idx, :]
            seg_node_idxs = self._grid_data.subset_node_indices['all'][i1:i2]
            w_b_i = self._w_b_i[seg_idx] = np.ones(n)
            tau_i = self._tau_i[seg_idx] = grid_data.node_stau[seg_node_idxs]
            # print(n, seg_node_idxs, tau_i, w_b_i)
            for j in range(n):
                for k in range(n):
                    if k != j:
                        w_b_i[j] /= (tau_i[j] - tau_i[k])

            self._l_idxs_from_g[seg_idx] = list(itertools.combinations(range(n)[::-1], n - 1))

            # These indices pertain to the upper triangular matrix (excluding the diagonal)
            self._dl_dg_idxs_from_g[seg_idx] = []
            for i, tup in enumerate(self._l_idxs_from_g[seg_idx]):
                self._dl_dg_idxs_from_g[seg_idx].extend(list(itertools.combinations(tup, n - 2))[i:])

        super().__init__(**kwargs)

    def setup(self):
        self.add_input('stau', shape=(self._vec_size,), units='unitless')
        if self._standalone_mode:
            # If in standalone_mode, assume interpolants were added prior to setup.
            self.configure_io()

    def set_segment_index(self, segment_index):
        """
        Set the index of the segment to be interpolated.

        Parameters
        ----------
        segment_index : int
            The index of the segment for which the interpolation is to be performed.
        """
        self._segment_index = segment_index

    def add_interp(self, name, input_name, output_name, shape, units):
        """
        Add a variable to be interpolated at configure time.

        Parameters
        ----------
        name : str
            A name associated with the interpolant.
        input_name : str
            The name of the input containing values to be interpolated at the nodes.
        output_name : str
            The name of the output containing the value interpolated at some given tau.
        shape : tuple
            The shape of the variable to be interpolated.
        units : str
            The units of the variable to be interpolated.
        """
        if name in self._interpolants:
            raise ValueError(f'{self.msginfo} : Attempted to add interpolant named {name} but one already exists.')
        if input_name in [options['input_name'] for options in self._interpolants.values()]:
            raise ValueError(f'{self.msginfo} : Attempted to add interpolant with input {input_name} but one '
                             f'already exists with this input name.')
        if output_name in [options['output_name'] for options in self._interpolants.values()]:
            raise ValueError(f'{self.msginfo} : Attempted to add interpolant with output {output_name} but one '
                             f'already exists with this output name.')

        self._interpolants[name] = {'input_name': input_name,
                                    'output_name': output_name,
                                    'shape': shape,
                                    'units': units}

    def configure_io(self):
        """
        Final configuration of the components inputs and outputs typically called during configure of some
        parent Group.
        """
        num_nodes = self._grid_data.subset_num_nodes['all']

        for interp_name, options in self._interpolants.items():
            input_name = options['input_name']
            output_name = options['output_name']
            shape = options['shape']
            units = options['units']

            self.add_input(input_name, shape=(num_nodes,) + shape, units=units)
            self.add_output(output_name, shape=(self._vec_size,) + shape, units=units)

            self.declare_partials(of=output_name, wrt=input_name, val=0.0)
            self.declare_partials(of=output_name, wrt='stau', val=0.0)

    def compute(self, inputs, outputs):
        """
        Compute component outputs.

        Parameters
        ----------
        inputs : `Vector`
            `Vector` containing inputs.
        outputs : `Vector`
            `Vector` containing outputs.
        """
        i1, i2 = self._grid_data.subset_segment_indices['all'][self._segment_index, :]
        w_b_i = self._w_b_i[self._segment_index]
        tau_i = self._tau_i[self._segment_index]
        seg_node_idxs = self._grid_data.subset_node_indices['all'][i1:i2]

        tau = inputs['stau']
        g = tau - tau_i

        # l_idxs_from_g = list(itertools.combinations(range(n)[::-1], n - 1))

        # This code block is replaced by precomputing the combinations of g that are multiplied to
        # form elements in l (l_idxs_from_g).
        # These indices are precomputed at setup and cached.
        # This makes evaluation about 3x faster when n=200.

        # n = len(seg_node_idxs)
        # for i in range(n):
        #     for j in range(n):
        #         if j != i:
        #             l[i] *= g[j]

        l = np.prod(g[self._l_idxs_from_g[self._segment_index]], axis=1)

        for interp_name, options in self._interpolants.items():
            u_hat = inputs[options['input_name']][seg_node_idxs, ...]
            wbfj = np.swapaxes(w_b_i * np.swapaxes(u_hat, 0, -1), -1, 0)
            outputs[options['output_name']] = np.einsum('i,ij...->j...', l, wbfj)

    def compute_partials(self, inputs, partials, discrete_inputs=None):
        i1, i2 = self._grid_data.subset_segment_indices['all'][self._segment_index, :]
        w_b_i = self._w_b_i[self._segment_index]
        tau_i = self._tau_i[self._segment_index]
        seg_node_idxs = self._grid_data.subset_node_indices['all'][i1:i2]
        n = len(seg_node_idxs)

        tau = inputs['stau']

        g = tau - tau_i
        dg_dtau = np.ones_like(tau_i)
        dl_dg = np.zeros((n, n))
        # As above, we replace these nested loops to improve performance as n becomes large.
        # l = np.ones_like(g, dtype=float)
        # for i in range(n):
        #     for j in range(n):
        #         if j != i:
        #             l[i] *= g[j]
        #             dl_dg[i, j] = 1.0
        #             for k in range(n):
        #                 if k != j and k != i:
        #                     dl_dg[i, j] *= g[k]

        dl_dg[np.triu_indices_from(dl_dg, k=1)] = np.prod(g[self._dl_dg_idxs_from_g[self._segment_index]], axis=1)
        dl_dg = dl_dg + dl_dg.T
        l = np.prod(g[self._l_idxs_from_g[self._segment_index]], axis=1)

        for interp_name, options in self._interpolants.items():
            u_hat = inputs[options['input_name']][seg_node_idxs, ...]
            shape = options['shape']
            size = np.prod(shape, dtype=int)
            wbfj = np.swapaxes(w_b_i * np.swapaxes(u_hat, 0, -1), -1, 0)
            d_output_dl = wbfj.T
            partials[options['output_name'], 'stau'] = d_output_dl @ dl_dg @ dg_dtau

            d_output_d_wbfj = np.repeat(l, size).reshape((n,) + shape).T
            d_wbfj_d_fj = w_b_i
            partials[options['output_name'], options['input_name']][..., seg_node_idxs] = d_output_d_wbfj * d_wbfj_d_fj
